# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3febf71369d6b8b25529ebc82530e6f21c22b0f88c1ece0bc17c913a56cfb4c89f5b55332d2055daa45b5400753366b39cc30ea75fdc9e0b6c5c6570563b5f4

test:
  secret_key_base: 438b22b9c57c9950e8ec37b39397885e258f9e95841c60da5b99257c40b99575031f9036f6c23689242ed405ec8a7815b7d11c5f94f0f21e7a9d617b05cf3edd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
